GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "second test",
    "author": "andres",
    "url": "https://example.com/blogposts/blogid"
}