GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "wwwwwahahawhw",
    "author": "andy type",
    "url": "https://urltesting.com",
    "userId": "222222ccc211cc2233"
}